version: 0.2

 

phases:

  install:

    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.

    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.

    runtime-versions:

      nodejs: 16

  pre_build:

    commands:

      - echo Installing source NPM dependencies...

      - npm install

  build:

    commands:

      - echo Build started on 'date'

      - npm run build

  post_build:

    commands:

      #- aws s3 cp --recursive ./build s3://kingdom-software-website/

      #- aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://kingdom-software-website/

      - aws cloudfront create-invalidation --distribution-id E37AHOSX2PPIZZ --paths /index.html

artifacts:

  files:

    - "build/*"

    - "build/**/*"